name: template_project
description: A new Flutter project.

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Version and build number for the application
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0' # This ensures compatibility with Flutter SDK versions

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons for Cupertino widgets
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint rules to encourage good coding practices
  flutter_lints: ^4.0.0

flutter:

  # Ensures that Material Icons font is included
  uses-material-design: true

  # Assets section: Add your assets here
  assets:
    # Uncomment to add image assets
    # - assets/images/dunia_sophie.jpg
    # - assets/images/laskar_pelangi.jpg

  # Fonts section: Uncomment to add custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
